title: Ali Faraji's Personal Website
email: ali@faraji.info
description: >-
  Personal website of Ali Faraji, a Mahine Learning Researcher
baseurl: ""
url: "https://faraji.info" 
twitter_username: AliFaraji312230
github_username:  alifa98

theme: null